services:
  frontend:
    container_name: course-sphere-frontend
    image: ${REGISTRY}/frontend:latest
    restart: always
    environment:
      DATABASE_URL: ${{ DATABASE_URL }}
    networks:
      - network

networks:
  network:
    name: course-sphere-network
    external: true
